apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vitessclusters.vitess.io
spec:
  group: vitess.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: vitessclusters
    singular: vitesscluster
    kind: VitessCluster
    shortNames: ["vt"]
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vitesscells.vitess.io
spec:
  group: vitess.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: vitesscells
    singular: vitesscell
    kind: VitessCell
    shortNames: ["vtc"]
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vitesskeyspaces.vitess.io
spec:
  group: vitess.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: vitesskeyspaces
    singular: vitesskeyspace
    kind: VitessKeyspace
    shortNames: ["vtk"]
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vitessshards.vitess.io
spec:
  group: vitess.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: vitessshards
    singular: vitessshard
    kind: VitessShard
    shortNames: ["vts"]
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: vitesscluster-controller
spec:
  parentResource:
    apiVersion: vitess.io/v1alpha1
    resource: vitessclusters
  childResources:
  - apiVersion: vitess.io/v1alpha1
    resource: vitesscells
    updateStrategy:
      method: RollingInPlace
      statusChecks:
        conditions:
        - type: Ready
          status: "True"
        - type: Updated
          status: "True"
  hooks:
    sync:
      webhook:
        url: http://vitess-operator.vitess/sync-cluster
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: vitesscell-controller
spec:
  parentResource:
    apiVersion: vitess.io/v1alpha1
    resource: vitesscells
  childResources:
  - apiVersion: v1
    resource: services
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: configmaps
    updateStrategy:
      method: InPlace
  - apiVersion: apps/v1beta2
    resource: deployments
    updateStrategy:
      method: RollingInPlace
      statusChecks:
        conditions:
        - type: Available
          status: "True"
        - type: Progressing
          status: "True"
          reason: NewReplicaSetAvailable
  - apiVersion: batch/v1
    resource: jobs
    updateStrategy:
      method: Recreate
  - apiVersion: etcd.database.coreos.com/v1beta2
    resource: etcdclusters
    updateStrategy:
      method: RollingInPlace
      statusChecks:
        conditions:
        - type: Available
          status: "True"
  - apiVersion: vitess.io/v1alpha1
    resource: vitesskeyspaces
    updateStrategy:
      method: RollingInPlace
      statusChecks:
        conditions:
        - type: Ready
          status: "True"
        - type: Updated
          status: "True"
  hooks:
    sync:
      webhook:
        url: http://vitess-operator.vitess/sync-cell
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: vitesskeyspace-controller
spec:
  parentResource:
    apiVersion: vitess.io/v1alpha1
    resource: vitesskeyspaces
  childResources:
  - apiVersion: vitess.io/v1alpha1
    resource: vitessshards
    updateStrategy:
      method: RollingInPlace
      statusChecks:
        conditions:
        - type: Ready
          status: "True"
        - type: Updated
          status: "True"
  hooks:
    sync:
      webhook:
        url: http://vitess-operator.vitess/sync-keyspace
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: vitessshard-controller
spec:
  parentResource:
    apiVersion: vitess.io/v1alpha1
    resource: vitessshards
  childResources:
  - apiVersion: v1
    resource: pods
    updateStrategy:
      method: RollingRecreate
      statusChecks:
        conditions:
        - type: Ready
          status: "True"
  - apiVersion: v1
    resource: persistentvolumeclaims
  hooks:
    sync:
      webhook:
        url: http://vitess-operator.vitess/sync-shard
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vitess-operator
  namespace: vitess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vitess-operator
  template:
    metadata:
      labels:
        app: vitess-operator
    spec:
      containers:
      - name: hooks
        image: metacontroller/jsonnetd:0.1
        imagePullPolicy: Always
        workingDir: /vt/operator/hooks
        volumeMounts:
        - name: hooks
          mountPath: /vt/operator/hooks
      volumes:
      - name: hooks
        configMap:
          name: vitess-operator-hooks
---
apiVersion: v1
kind: Service
metadata:
  name: vitess-operator
  namespace: vitess
spec:
  selector:
    app: vitess-operator
  ports:
  - port: 80
    targetPort: 8080
